version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: parapp_db
    env_file: ".env"
    profiles: [main]
    ports:
      - "5432:5432"
    volumes:
      - parapp_db1:/var/lib/postgresql/data # Persist database data
      - ./db:/db

  app:
    build: .
    profiles: [main]
    depends_on:
      - postgres
    network_mode: host
    env_file: ".env"

volumes:
  parapp_db1:
