version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: parapp_db
    env_file: ".env"
    profiles: [main]
    ports:
      - "5432:5432"
    volumes:
      - parapp_db1:/var/lib/postgresql/data # Persist database data
      - ./db:/db

  app:
    build: .
    profiles: [main]
    depends_on:
      - postgres
    network_mode: host
    env_file: ".env"

  varnish:
    image: varnish:latest
    container_name: varnish_cache
    network_mode: host
    # depends_on:
    #   - app
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
    command: >
      varnishd -F -f /etc/varnish/default.vcl -s malloc,32m -a http=:18125

volumes:
  parapp_db1:
